/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ViewsRouteImport } from './routes/views'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryRunIdRouteImport } from './routes/history.$runId'
import { Route as VViewIdRouteImport } from './routes/v.$viewId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsRoute = ViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRunIdRoute = HistoryRunIdRouteImport.update({
  id: '/history/$runId',
  path: '/history/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const VViewIdRoute = VViewIdRouteImport.update({
  id: '/v/$viewId',
  path: '/v/$viewId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/views': typeof ViewsRoute
  '/history/$runId': typeof HistoryRunIdRoute
  '/v/$viewId': typeof VViewIdRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/views': typeof ViewsRoute
  '/history/$runId': typeof HistoryRunIdRoute
  '/v/$viewId': typeof VViewIdRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/views': typeof ViewsRoute
  '/history/$runId': typeof HistoryRunIdRoute
  '/v/$viewId': typeof VViewIdRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/views' | '/history/$runId' | '/v/$viewId' | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/views' | '/history/$runId' | '/v/$viewId' | '/history'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/views'
    | '/history/$runId'
    | '/v/$viewId'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ViewsRoute: typeof ViewsRoute
  HistoryRunIdRoute: typeof HistoryRunIdRoute
  VViewIdRoute: typeof VViewIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views': {
      id: '/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof ViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$runId': {
      id: '/history/$runId'
      path: '/history/$runId'
      fullPath: '/history/$runId'
      preLoaderRoute: typeof HistoryRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$viewId': {
      id: '/v/$viewId'
      path: '/v/$viewId'
      fullPath: '/v/$viewId'
      preLoaderRoute: typeof VViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ViewsRoute: ViewsRoute,
  HistoryRunIdRoute: HistoryRunIdRoute,
  VViewIdRoute: VViewIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
