# --- SQLite ---
spring.datasource.url=jdbc:sqlite:${DB_PATH:weather.db}?foreign_keys=on&busy_timeout=5000
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.hikari.maximum-pool-size=1

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
