name: Build and Push Dev Images

on:
  push:
    branches:
      - main
    paths:
      - '02-development/backend/**'
      - '02-development/frontend/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: ${{ github.repository_owner }}/weather-backend
  IMAGE_NAME_FRONTEND: ${{ github.repository_owner }}/weather-frontend

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./02-development/backend
          file: ./02-development/backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:dev

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./02-development/frontend
          file: ./02-development/frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:dev
